import Head from "next/head";
import styles from "./Layout.module.css";
import Logo from "./logo";

function Layout({ children, title = "World Ranks" }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Logo />
      <main className={styles.main}>{children}</main>
      <footer className={styles.footer}>Kishan Italiya</footer>
    </div>
  );
}

export default Layout;
